### ISSUE TITLE
Service often be disrupted. Need to start again

### ISSUE THREAD

**Issue by StevenTruong89** [sh2/gemini-mattermost-bot#1]
Hi, first at all I would like to say thanks for amazing repo. Currently I have an issue that service often be disrupted, bot don't reply anything. So I need to start again by using "./script.sh". 

In additionally, script build docker container can't run.  You please help to improve when have time. thank you

```
[ERROR] Exception:
Traceback (most recent call last):
  File "/root/gemini-mattermost-bot/chat-bot/gemini-chat-bot.py", line 102, in respond
    response = self.gemini_model.generate_content(
  File "/root/gemini-mattermost-bot/chat-bot/.venv/lib64/python3.9/site-packages/google/generativeai/generative_models.py", line 248, in generate_content
    response = self._client.generate_content(request)
  File "/root/gemini-mattermost-bot/chat-bot/.venv/lib64/python3.9/site-packages/google/ai/generativelanguage_v1beta/services/generative_service/client.py", line 566, in generate_content
    response = rpc(
  File "/root/gemini-mattermost-bot/chat-bot/.venv/lib64/python3.9/site-packages/google/api_core/gapic_v1/method.py", line 131, in __call__
    return wrapped_func(*args, **kwargs)
  File "/root/gemini-mattermost-bot/chat-bot/.venv/lib64/python3.9/site-packages/google/api_core/retry.py", line 372, in retry_wrapped_func
    return retry_target(
  File "/root/gemini-mattermost-bot/chat-bot/.venv/lib64/python3.9/site-packages/google/api_core/retry.py", line 207, in retry_target
    result = target()
  File "/root/gemini-mattermost-bot/chat-bot/.venv/lib64/python3.9/site-packages/google/api_core/timeout.py", line 120, in func_with_timeout
    return func(*args, **kwargs)
  File "/root/gemini-mattermost-bot/chat-bot/.venv/lib64/python3.9/site-packages/google/api_core/grpc_helpers.py", line 79, in error_remapped_callable
    return callable_(*args, **kwargs)
  File "/root/gemini-mattermost-bot/chat-bot/.venv/lib64/python3.9/site-packages/google/ai/generativelanguage_v1beta/services/generative_service/transports/rest.py", line 856, in __call__
    raise core_exceptions.from_http_response(response)
google.api_core.exceptions.BadRequest: 400 POST https://generativelanguage.googleapis.com/v1beta/models/gemini-pro:generateContent?%24alt=json%3Benum-encoding%3Dint: Please ensure that multiturn requests ends with a user role or a function response.
```

**Comment by sh2** [comment]
Thank you very much for your report.
The Gemini API raises an exception if user and model do not alternate in their statements. (The OpenAI API, on the other hand, works even if they do not alternate.)
Please check who is speaking in what order in the thread of the conversation.
Also, the current version does not check the maximum number of tokens, so you may get an error if the conversation is too long.
If you don't mind, what API request was made just before this Exception? For example,
```
[01/10/2024 07:21:25][gemini-chat-bot][INFO] API Request: [
{"role": "user", "parts": ["Context: You are an assistant AI.\nMessage:  Hello, how are you?"]},
{"role": "model", "parts": ["As an AI assistant, I am unable to experience emotions or states of being, including wellness. However, I can assist you with a wide range of tasks and questions. How can I assist you today?"]},
{"role": "user", "parts": ["Message: What are the new events for the Paris Olympics?"]}
]
```

**Comment by StevenTruong89** [comment]
thanks for reply quickly. I followed your instrcution and until now I don't face that problem anymore.
So can you take a look about docker? It seem can't use, right now I'm launching Python scripts directly.

**Comment by sh2** [comment]
Glad to hear that the first problem has been resolved.

So you were able to build the container, but were unable to get it up and running.
The first thing you need to check is the MATTERMOST_URL.
The MATTERMOST_URL you should specify may be different when launching a Python script directly and when launching a container.
If the Mattermost server is running on the same host, you would specify http://localhost or http://127.0.0.1 for direct Python script invocation, but this is incorrect in a container environment because it would point to the container itself.
The correct configuration in this case would be an address such as 192.168.x.x or 172.x.x.x, for example.
Try the following to find the IP address from which you can access Mattermost from the container.
```
$ podman run -it ubuntu:22.04
# apt update
# apt install curl
# curl http://192.168.x.x
```
If this does not solve the problem, check the container logs with the podman logs command.
